version: '3.9'
services:
  postgres:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: shah
      POSTGRES_DB: bookingdb
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: